#ifndef PLUGIN_API_H
#define PLUGIN_API_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Display dimensions
#define DISPLAY_WIDTH 128

#define DISPLAY_HEIGHT 128

#define FRAMEBUFFER_SIZE (DISPLAY_WIDTH * DISPLAY_HEIGHT)

// Plugin magic number and version
#define PLUGIN_MAGIC 1347179847

#define PLUGIN_API_VERSION 1

#define INPUT_UP (1 << 0)

#define INPUT_DOWN (1 << 1)

#define INPUT_LEFT (1 << 2)

#define INPUT_RIGHT (1 << 3)

#define INPUT_A (1 << 4)

#define INPUT_B (1 << 5)

#define INPUT_START (1 << 6)

#define INPUT_SELECT (1 << 7)

// Direct framebuffer access structure
typedef struct FrameBuffer {
  // Raw pixel data in RGB565 format
  uint16_t pixels[FRAMEBUFFER_SIZE];
  // Display width (always 128)
  uint32_t width;
  // Display height (always 128)
  uint32_t height;
  // Current frame counter
  uint32_t frame_counter;
} FrameBuffer;

// Graphics helper functions
typedef struct GraphicsContext {
  void (*set_pixel)(int32_t x, int32_t y, uint16_t color);
  uint16_t (*get_pixel)(int32_t x, int32_t y);
  void (*clear)(uint16_t color);
  void (*fill_rect)(int32_t x, int32_t y, int32_t w, int32_t h, uint16_t color);
  void (*draw_line)(int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint16_t color);
  void (*draw_circle)(int32_t cx, int32_t cy, int32_t radius, uint16_t color);
  void (*blit)(int32_t x, int32_t y, int32_t w, int32_t h, const uint16_t *data);
} GraphicsContext;

// System utilities
typedef struct SystemContext {
  uint32_t (*random)(void);
  uint32_t (*millis)(void);
  uint16_t (*rgb)(uint8_t r, uint8_t g, uint8_t b);
  uint16_t color_red;
  uint16_t color_green;
  uint16_t color_blue;
  uint16_t color_white;
  uint16_t color_black;
  uint16_t color_yellow;
  uint16_t color_cyan;
  uint16_t color_magenta;
} SystemContext;

// Main API structure passed to plugins
typedef struct PluginAPI {
  // Direct framebuffer access
  struct FrameBuffer *framebuffer;
  // Graphics context with drawing helpers
  const struct GraphicsContext *gfx;
  // System utilities
  const struct SystemContext *sys;
} PluginAPI;

// Plugin header
typedef struct PluginHeader {
  uint32_t magic;
  uint32_t api_version;
  uint8_t name[32];
  int32_t (*init)(const struct PluginAPI *api);
  void (*update)(const struct PluginAPI *api, uint32_t inputs);
  void (*cleanup)(void);
} PluginHeader;

#endif  /* PLUGIN_API_H */
