[package]
name = "cluster-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics-common = { path = "../../graphics-common" }
cluster-core = { path = "../../cluster-core", default-features = false }

[features]
default = []
std = []